version: '3'

services:
    db:
        container_name: db
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        volumes:
            - ./db/sql:/docker-entrypoint-initdb.d/
            - ./db/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: nodedb
            MYSQL_ROOT_PASSWORD: root
        networks:
            - node-network

    app:
        container_name: app
        build: ./app
        tty: true
        depends_on:
            - db
        networks:
            - node-network

    proxy:
        container_name: proxy
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
            - app
        networks:
            - node-network

networks:
    node-network:
        driver: bridge
